version: '3'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    environment:
      NODE_ENV: production

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    volumes:
      - ./server/db/cars.db:/usr/src/server/db/cars.db
    environment:
      NODE_ENV: production
